# Generated by Django 4.0.6 on 2022-07-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Os_platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LN', 'Linux'), ('WD', 'Windows')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='Easy to setup', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='os_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price',
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(default='Best service', max_length=255),
        ),
        migrations.CreateModel(
            name='Service_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('os_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.os_platform')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
