# Generated by Django 4.0.6 on 2022-07-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_os_platform_remove_services_os_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_price',
            old_name='os_id',
            new_name='os',
        ),
        migrations.RenameField(
            model_name='service_price',
            old_name='service_id',
            new_name='service',
        ),
    ]
