# Generated by Django 4.0.6 on 2022-07-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_os_id_service_price_os_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Os_platform',
            new_name='OsPlatform',
        ),
        migrations.RenameModel(
            old_name='Service_price',
            new_name='ServicePrice',
        ),
    ]
